# Generated by Django 2.1.3 on 2019-03-04 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('picture', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_status', models.IntegerField()),
                ('organisations', models.CharField(max_length=1000)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='org',
            unique_together={('picture', 'address')},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='orgUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.OrgUser'),
        ),
        migrations.AddField(
            model_name='admin',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.Org'),
        ),
    ]
