# Generated by Django 2.1.3 on 2019-03-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20190304_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.ChatMessage')),
            ],
        ),
    ]
