# Generated by Django 2.1.3 on 2019-03-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Org'),
        ),
    ]
