# Generated by Django 2.1.3 on 2019-03-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190318_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='orgUserId',
            new_name='org_user_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_message',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.ChatMessage'),
        ),
    ]
